{% set name = "git_root" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jtilly/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 36aeb4e48e182a7090fb9dfb062aba9e53f9d82c3e4ffeab922c270513ae4478

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - git_root

about:
  home: https://github.com/jtilly/git_root
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Find the root of a git repo'
  description: 'Find the root of a git repo'
  dev_url: https://github.com/jtilly/git_root

extra:
  recipe-maintainers:
    - jtilly
