travis:
  secure:
    BINSTAR_TOKEN: MwyheccUAaKFZRPiW/N6Nf/oR7oqSlbAelSUJ9F0JEVu/rtOgw0z6n3we36iGpSAbI/wypHmldfv2hYd7eCJd9LJt1Mx7CMFQ2x9SyDDlb/E2TsHVtMZa8fNoaSrjUGHNJFuF5XJ4KRULnMWMMeMIpo0CBiBdkvdDJ5TQIpTygZcDvUmMvjIQVbxWMvbIjtpJQ+VkmYyoQkcOX5LtDysh9YhL5jAi5fJ5zJMS08nEx1kytOSClwZWYAKjGxDPY4e0A+zPzA6o+twMJ4fsR47E6KenyxWXw6QBsQ42bpiIhG/CR0/ucSBHfJ9KSahm3ZYurmvX7yqqwG/17MeMxtweHJk0hUgjMBDhS06L/N6nM9oyPio0BGyNYHudvenugHF6ktLy/uvdSp+a5j2tEUtpkdPxQn1Tw+Hc00eYgTNrnT7B+IlgDXwhZYjstERdyNcWNAm4VUnL16k6X8WtxF1ie0kEPzSAURUHlGMke/uJit9egcNiHoo7RON77a63AwaaqS02iyPyo+YvW9VnSQNlsJIFShjULzRxJuCHQZ864YGF3KTmHFaUEbJH4jS9sW6CPZeMWZs+daf+0WgiLLaKCq1JVWiqZYxGX9IzULMEIzRIOtb6jtreI/4uKbB+GssU/xGKZ+kV6x1z4SdVfRV2mm5q3wWQRjYevgtBmXjseE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
